export const routes = [
  {
    path: "/",
    component: "Home",
    changefreq: "weekly",
    priority: 1,
  },
  {
    path: "/contribute",
    component: "Contribute",
    changefreq: "monthly",
    priority: 0.8,
  },
  {
    path: "/simulations",
    component: "Simulations",
    changefreq: "weekly",
    priority: 0.9,
  },
  {
    path: "/about",
    component: "About",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog",
    component: "Blog",
    changefreq: "weekly",
    priority: 0.9,
  },
  {
    path: "/blog/create",
    component: "Blog",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog/what-is-physics",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/class-12-physics-complete-guide",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/physics-bouncing-ball-comprehensive-educational-guide",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/comprehensive-guide-to-vector-operations",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/ball-uniformly-accelerated-motion",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/ball-free-fall-comprehensive-guide",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/spring-connection",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/physics-of-pendulum-explained",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/projectile-parabolic-motion",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/physics-behind-three-body-problem",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/blog/pi-from-block-collisions-explained",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/BouncingBall",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/VectorsOperations",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/BallAcceleration",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/BallGravity",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/SpringConnection",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/SimplePendulum",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/ParabolicMotion",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/InclinedPlane",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/CircularMotion",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/ThreeBody",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/HorizontalSpring",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/DoublePendulum",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/CollisionSimulation",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/test",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
  {
    path: "/simulations/PiCollisions",
    changefreq: "weekly",
    priority: 0.7,
    lastmod: "2026-07-04",
  },
];
